Repository FE5-TEAM9/sweethome, pull requests merged in 2023-06, with the labels that each got.

#7 Feat(fe): 홍빈 테스트 페이지 구현
  src/components/HongBin.tsx
Labels: enhancement

#8 Feat(fe): 은상 테스트 페이지 구현
  README.md
  package-lock.json
  src/components/ChoEunSang.tsx
Labels: enhancement

#9 Feat(fe): 준희 테스트 페이지 구현
  src/components/KimJuneHee.tsx
Labels: enhancement

#10 Feat(fe): 동은 테스트 페이지 구현
  src/components/Dongeun.tsx
Labels: enhancement

#14 Remove(fe): 불필요한 파일 삭제
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/components/ChoEunSang.tsx
  src/components/Dongeun.tsx
  src/components/HongBin.tsx
  src/components/KimJuneHee.tsx
  src/components/parkKeunWoo.tsx
  src/index.css
Labels: remove

#21 Docs(fe): Footer 생성 및 Common SCSS 수정
  index.html
  src/components/TheFooter.tsx
  src/routes/Home.tsx
  src/styles/TheFooter.scss
  src/styles/common/fonts.scss
Labels: documentation

#23 Docs(fe): 절대경로 인식 오류 수정
  tsconfig.json
  vite.config.ts
Labels: documentation

#24 Feat(fe): 회원가입 페이지 구현
  src/routes/SignUp.tsx
  src/routes/index.tsx
  src/styles/SignUp.scss
Labels: enhancement

#29 Feat(fe): Header Component 구현
  package-lock.json
  package.json
  src/components/TheHeader.tsx
  src/routes/About.tsx
  src/routes/Home.tsx
  src/styles/TheHeader.scss
  src/styles/common/fonts.scss
  vite.config.ts
Labels: enhancement

#33 Feat(fe): 회원가입 기능 구현, API 연결
  src/App.tsx
  src/api/requests.ts
  src/components/TheHeader.tsx
  src/main.tsx
  src/routes/About/About.tsx
  src/routes/SignUp/SignUp.tsx
  src/routes/index.tsx
  src/styles/SignUp.module.scss
Labels: enhancement

#34 Docs(fe): 라우터 수정, 헤더 SCSS 수정
  src/components/TheHeader.tsx
  src/routes/index.tsx
  src/styles/TheHeader.module.scss
Labels: enhancement

#37 Feat(fe): 회원가입 Event Handler 타입 추가
  src/routes/SignUp/SignUp.tsx
Labels: enhancement

#39 Style(fe): Footer SCSS 모듈화, 클래스명 수정
  src/components/TheFooter.tsx
  src/styles/TheFooter.module.scss
Labels: documentation

#41 Style(fe): 회원가입 width, margin 수정
  src/styles/SignUp.module.scss
Labels: documentation

#45 Feat(fe): 마이 페이지 구현
  src/components/MyPage/Account/Account.tsx
  src/components/MyPage/Account/AccountList.tsx
  src/components/MyPage/Account/AccountModal.tsx
  src/components/MyPage/MyInfo/MyInfo.tsx
  src/routes/Mypage/Mypage.tsx
  src/routes/Mypage/MypageConfirm.tsx
  src/styles/Account.module.scss
  src/styles/AccountList.module.scss
  src/styles/AccountModal.module.scss
  src/styles/MyInfo.module.scss
  src/styles/Mypage.module.scss
  src/styles/MypageConfirm.module.scss
Labels: enhancement

#46 Feat(fe): Admin 페이지 기본 레이아웃 구성
  src/routes/Admin/Admin.tsx
  src/routes/Admin/AdminDashboard.tsx
  src/routes/Admin/AdminOrder.tsx
  src/routes/Admin/AdminProduct.tsx
  src/routes/Admin/AdminUser.tsx
  src/styles/Admin.module.scss
Labels: enhancement

#50 Feat(fe): 로그인 페이지 구현
  src/routes/Login/Login.tsx
  src/styles/Login.module.scss
Labels: enhancement

#51 Feat(fe): 상품 리스트 페이지 구현
  src/assets/products/bedroom1-detail.jpeg
  src/assets/products/bedroom1.jpeg
  src/assets/products/bedroom2-detail.jpeg
  src/assets/products/bedroom2.jpeg
  src/assets/products/kitchen1-detail.jpeg
  src/assets/products/kitchen1.jpeg
  src/assets/products/kitchen2-detail.jpeg
  src/assets/products/kitchen2.jpeg
  src/assets/products/kitchen3-detail.jpeg
  src/assets/products/kitchen3.jpeg
  src/components/MyPage/Account/AccountList.tsx
  src/components/MyPage/Account/AccountModal.tsx
  src/components/Shop/ProductItem.tsx
  src/routes/Mypage/Mypage.tsx
  src/routes/Shop/Shop.tsx
  src/styles/Account.module.scss
  src/styles/AccountList.module.scss
  src/styles/AccountModal.module.scss
  src/styles/ProductItem.module.scss
  src/styles/Shop.module.scss
  src/styles/SignUp.module.scss
Labels: enhancement

#52 Feat(fe): 메인 페이지 구현
  package-lock.json
  package.json
  src/App.tsx
  src/routes/Home/Home.tsx
  src/styles/Home.module.scss
  src/styles/Slider.module.scss
  src/utils/slider.tsx
  yarn.lock
Labels: enhancement

#53 Feat(fe): 로그인 기능 구현
  src/routes/Login/Login.tsx
Labels: enhancement

#58 Design(fe): 로그인 페이지 디자인 수정
  src/api/requests.ts
  src/routes/Login/Login.tsx
  src/routes/SignUp/SignUp.tsx
  src/styles/Login.module.scss
Labels: documentation

#60 Style(fe): 코드 수정
  src/components/MyPage/MyInfo/MyInfo.tsx
  src/routes/SignUp/SignUp.tsx
Labels: documentation

#61 Feat: admin 페이지 상품 등록 폼 구현
  public/assets/products/bedroom1-detail.jpeg
  public/assets/products/bedroom1.jpeg
  public/assets/products/bedroom2-detail.jpeg
  public/assets/products/bedroom2.jpeg
  public/assets/products/kitchen1-detail.jpeg
  public/assets/products/kitchen1.jpeg
  public/assets/products/kitchen1.jpg
  public/assets/products/kitchen2-detail.jpeg
  public/assets/products/kitchen2.jpeg
  public/assets/products/kitchen3-detail.jpeg
  public/assets/products/kitchen3.jpeg
  src/api/requests.ts
  src/routes/Admin/AdminProduct.tsx
  src/styles/AdminProduct.module.scss
  yarn.lock
Labels: enhancement

#63 Feat(fe): admin 상품등록 페이지 상품 등록/삭제 구현
  src/api/requests.ts
  src/routes/Admin/AdminProduct.tsx
Labels: enhancement

#64 Feat(fe): 사용자 목록 조회 API 연결
  src/api/requests.ts
  src/routes/Admin/AdminProduct.tsx
  src/routes/Admin/AdminUser.tsx
  src/styles/Admin.module.scss
  src/styles/AdminProduct.module.scss
  src/styles/AdminUser.module.scss
  src/styles/common/fonts.scss
  yarn.lock
Labels: enhancement

#71 Feat(fe): 사용자 목록 API 연결
  src/styles/Admin/AdminProduct.module.scss
  src/styles/Admin/AdminUser.module.scss
Labels: enhancement

#74 Feat(fe): 로그인 인증 구현
  src/App.tsx
  src/api/requests.ts
Labels: enhancement

#78 Style(fe): Admin 상품 관리 SCSS 수정
  src/routes/Admin/AdminProduct.tsx
  src/styles/Admin/Admin.module.scss
  src/styles/Admin/AdminProduct.module.scss
Labels: documentation

#80 Feat(fe): 개인 정보 수정 유효성 검사 구현
  src/api/requests.ts
  src/routes/Mypage/MyInfo.tsx
  src/styles/Mypage/MyInfo.module.scss
Labels: enhancement

#82 Feat(fe): 마이페이지 - 비밀번호 수정 기능 구현
  src/App.tsx
  src/api/requests.ts
  src/routes/Mypage/MyInfo.tsx
Labels: enhancement

#84 Chore(fe): MyInfo 파일 코드 수정
  src/routes/Mypage/MyInfo.tsx
Labels: documentation

#88 Feat(fe): 계좌 관리 기능 추가
  src/api/requests.ts
  src/components/MyPage/Account/Account.tsx
  src/components/MyPage/Account/AccountList.tsx
  src/components/MyPage/Account/AccountModal.tsx
  src/components/MyPage/MyInfo/MyInfo.tsx
  src/routes/Mypage/AccountList.tsx
  src/routes/Mypage/Mypage.tsx
  src/routes/Mypage/MypageConfirm.tsx
  src/styles/Mypage/AccountModal.module.scss
  src/styles/Mypage/Mypage.module.scss
Labels: enhancement

#85 Feat(fe): 리덕스 적용
  package-lock.json
  package.json
  src/api/requests.ts
  src/main.tsx
  src/reducers/index.ts
  src/reducers/info.ts
  src/routes/Home/Home.tsx
  src/routes/Login/Login.tsx
  src/store/index.ts
  yarn.lock
Labels: enhancement

#89 Feat(fe): Shop 상품 리스트 페이지, 기능 구현
  src/api/requests.ts
  src/components/Shop/ProductItem.tsx
  src/routes/Admin/AdminProduct.tsx
  src/routes/Shop/Shop.tsx
  src/styles/Shop/ProductItem.module.scss
  yarn.lock
Labels: enhancement

#91 Design(fe): Shop 상품 리스트 SCSS 출력
  src/components/Shop/ProductItem.tsx
  src/routes/Shop/Shop.tsx
  src/styles/Shop/ProductItem.module.scss
Labels: documentation

#95 Feat(fe): Shop 상품 리스트 filter 기능 추가
  src/api/requests.ts
  src/components/TheModal.tsx
  src/routes/Admin/Admin.tsx
  src/routes/Admin/AdminProduct.tsx
  src/routes/Shop/Shop.tsx
  src/styles/Admin/Admin.module.scss
  src/styles/Shop/Shop.module.scss
  src/styles/TheModal.module.scss
Labels: enhancement

#96 Design(fe): Shop 상품 상세 페이지 UI 구현
  src/api/requests.ts
  src/components/Shop/ProductItem.tsx
  src/routes/Shop/Shop.tsx
  src/routes/Shop/ShopDetail.tsx
  src/styles/Shop/Shop.module.scss
  src/styles/Shop/ShopDetail.module.scss
Labels: documentation

#97 Fix(fe): Shop 상품 상세 페이지 단일 상품 조회 API 수정
  src/routes/Shop/ShopDetail.tsx
  src/routes/index.tsx
Labels: bug

#99 Chore(fe): 코드 수정
  src/api/requests.ts
  src/routes/Mypage/MyInfo.tsx
  src/routes/Mypage/Mypage.tsx
Labels: documentation

#100 Feat(fe): Cart 장바구니 리덕스 연결
  src/components/Shop/ProductItem.tsx
  src/reducers/cart.ts
  src/reducers/index.ts
  src/routes/Shop/Shop.tsx
  src/routes/Shop/ShopDetail.tsx
  src/styles/Shop/ProductItem.module.scss
Labels: enhancement

#101 Style(fe): 마이페이지 스타일 수정
  src/components/MyPage/Account/Account.tsx
  src/routes/Mypage/Mypage.tsx
  src/styles/Mypage/Mypage.module.scss
Labels: documentation

#104 Refactor(fe): 마이페이지 AccountModal 수정
  public/assets/bank/bank004.svg
  public/assets/bank/bank011.svg
  public/assets/bank/bank020.svg
  public/assets/bank/bank081.svg
  public/assets/bank/bank088.svg
  public/assets/bank/bank089.svg
  public/assets/bank/bank090.svg
  src/api/requests.ts
  src/components/MyPage/Account/Account.tsx
  src/components/MyPage/Account/AccountModal.tsx
  src/routes/Mypage/AccountList.tsx
  src/routes/Mypage/MyInfo.tsx
  src/routes/Mypage/Mypage.tsx
  src/routes/SignUp/SignUp.tsx
  src/styles/Mypage/Account.module.scss
  src/styles/Mypage/AccountList.module.scss
  src/styles/Mypage/AccountModal.module.scss
  src/styles/Mypage/MyInfo.module.scss
  src/styles/Mypage/Mypage.module.scss
  src/styles/SignUp/SignUp.module.scss
Labels: documentation

#105 Feat(fe): 로그인 상태에 따른 반응형 Header 추가
  src/components/TheHeader.tsx
  src/reducers/index.ts
  src/reducers/logout.ts
  src/routes/Login/Login.tsx
  src/styles/TheHeader.module.scss
Labels: enhancement

#106 Style(fe): placeholder 추가
  src/components/MyPage/Account/AccountModal.tsx
  src/routes/Mypage/MyInfo.tsx
Labels: documentation

#109 Fix(fe): Header 로그인,로그아웃 버그 수정
  src/components/TheHeader.tsx
  src/reducers/logout.ts
  src/routes/Login/Login.tsx
Labels: bug

#110 Fix(fe): 로그아웃시 Header 회원가입 버튼 숨김
  src/components/TheHeader.tsx
Labels: bug

#111 Feat(fe): 장바구니 페이지 구현
  src/components/Cart/CartList.tsx
  src/components/MyPage/Account/Account.tsx
  src/components/MyPage/Account/AccountModal.tsx
  src/routes/Cart/Cart.tsx
  src/routes/Mypage/AccountList.tsx
  src/routes/Shop/ShopDetail.tsx
  src/styles/Cart/Cart.module.scss
  src/styles/Cart/CartList.module.scss
Labels: enhancement

#113 Design(fe): About 페이지 대표 이미지, 소개글 추가
  public/assets/Home/main1.jpeg
  public/assets/Home/main2.jpeg
  public/assets/Home/main3.jpeg
  public/assets/about/about.jpeg
  src/routes/About/About.tsx
  src/styles/About/About.module.scss
  src/utils/slider.tsx
Labels: documentation

#115 Feat(fe): 선택상품 주문 네비게이션 구현
  src/components/Cart/CartList.tsx
  src/reducers/index.ts
  src/reducers/selectedCart.ts
  src/routes/Buy/Buy.tsx
  src/routes/Cart/Cart.tsx
  src/routes/index.tsx
  src/styles/Buy/Buy.module.scss
Labels: enhancement

#117 Feat(fe): 장바구니 페이지 구현
  src/api/requests.ts
  src/reducers/account.ts
  src/reducers/index.ts
  src/routes/Buy/Buy.tsx
  src/routes/Mypage/AccountList.tsx
  src/styles/Buy/Buy.module.scss
  src/styles/Cart/CartList.module.scss
  src/styles/Mypage/Account.module.scss
Labels: enhancement

#122 Feat(fe): 주문 내역 관리 구현
  src/api/requests.ts
  src/components/Cart/CartList.tsx
  src/components/MyPage/MyBankAccount/Account.tsx
  src/components/MyPage/MyBankAccount/AccountModal.tsx
  src/components/common/Loading.tsx
  src/components/common/SubNav.tsx
  src/routes/Buy/Buy.tsx
  src/routes/Cart/Cart.tsx
  src/routes/Mypage/MyBankAccount.tsx
  src/routes/Mypage/MyOrder.tsx
  src/routes/Mypage/MyOrderDetails.tsx
  src/routes/Mypage/Mypage.tsx
  src/routes/Mypage/Transactions.tsx
  src/styles/Loading.module.scss
  src/styles/Mypage/MyBankAccount.module.scss
  src/styles/Mypage/MyOrder.module.scss
  src/styles/Mypage/MyOrderDetails.module.scss
  src/styles/SubNav.module.scss
  src/utils/convert.ts
  src/utils/slider 2.tsx
Labels: enhancement

#125 Feat(Fe): adminOrder 페이지 구현
  src/api/requests.ts
  src/routes/Admin/Admin.tsx
  src/routes/Admin/AdminOrder.tsx
  src/routes/Buy/Buy.tsx
  src/styles/Admin/AdminOrder.module.scss
Labels: enhancement

#126 Fix(fe): 결제 이후 장바구니 업데이트
  src/components/Cart/CartList.tsx
  src/components/common/TheSearchBar.tsx
  src/routes/Buy/Buy.tsx
  src/routes/Cart/Cart.tsx
  src/styles/TheHeader.module.scss
  src/styles/TheSearchBar.module.scss
Labels: enhancement

#130 Feat(fe): 마이페이지 코드 수정
  src/components/MyPage/MyBankAccount/AccountModal.tsx
  src/routes/Mypage/Mypage.tsx
Labels: documentation

#132 Fix(fe): 메인 페이지 carousel 보완
  src/routes/Home/Home.tsx
  src/styles/Home/Home.module.scss
  src/styles/TheHeader.module.scss
  src/styles/utils/Slider.module.scss
  src/utils/slider.tsx
Labels: documentation

#134 Feat(fe): adminProduct 페이지 수정
  src/api/requests.ts
  src/components/common/Select.tsx
  src/components/common/SubNav.tsx
  src/components/common/TheModal.tsx
  src/components/common/TheSearchBar.tsx
  src/constants/index.ts
  src/routes/Admin/AdminOrder.tsx
  src/routes/Admin/AdminProduct.tsx
  src/routes/Login/Login.tsx
  src/routes/Mypage/MyOrder.tsx
  src/routes/Shop/Shop.tsx
  src/routes/Shop/ShopDetail.tsx
  src/styles/Admin/AdminOrder.module.scss
  src/styles/Login/Login.module.scss
  src/styles/Mypage/AccountModal.module.scss
  src/styles/Mypage/MyOrder.module.scss
  src/styles/Shop/ShopDetail.module.scss
  src/styles/TheModal.module.scss
Labels: enhancement

#135 Fix(fe): 상품 바로구매 로직 구현
  src/routes/Buy/Buy.tsx
  src/routes/Shop/ShopDetail.tsx
Labels: bug

#136 Feat(fe): UI, 페이지별 라이팅 개선
  src/components/Cart/CartList.tsx
  src/components/common/TheHeader.tsx
  src/components/common/TheSearchBar.tsx
  src/routes/Buy/Buy.tsx
  src/routes/Home/Home.tsx
  src/routes/Login/Login.tsx
  src/routes/Shop/ShopDetail.tsx
  src/routes/SignUp/SignUp.tsx
  src/styles/Home/Home.module.scss
  src/styles/Shop/ShopDetail.module.scss
  src/styles/TheHeader.module.scss
  src/styles/TheSearchBar.module.scss
  src/styles/utils/Slider.module.scss
  src/utils/slider.tsx
Labels: enhancement

#137 Feat(fe): 검색창, admin 관리자 라이팅 수정
  src/components/common/TheHeader.tsx
  src/routes/Admin/Admin.tsx
  src/routes/Login/Login.tsx
Labels: enhancement

#139 Feat(fe): 환경변수 세팅
  .gitignore
  src/api/requests.ts
  src/constants/index.ts
  src/routes/Login/Login.tsx
  src/routes/Mypage/Mypage.tsx
Labels: enhancement

#140 Chore(fe): yarn.lock 패키지 삭제
  yarn 2.lock
  yarn.lock
Labels: enhancement

#141 Feat(fe): 타입스크립트 추가
  src/App.tsx
  src/api/requests.ts
  src/components/MyPage/MyBankAccount/Account.tsx
  src/components/MyPage/MyBankAccount/AccountModal.tsx
  src/components/common/Select.tsx
  src/components/common/TheHeader.tsx
  src/components/common/TheModal.tsx
  src/components/common/TheSearchBar.tsx
  src/routes/Admin/AdminDashboard.tsx
  src/routes/Admin/AdminOrder.tsx
  src/routes/Admin/AdminProduct.tsx
  src/routes/Admin/AdminUser.tsx
  src/routes/Mypage/MyBankAccount.tsx
  src/styles/Admin/AdminDashBoard.module.scss
Labels: enhancement

#142 Feat(fe): 타입스크립트 추가
  src/api/requests.ts
  src/components/Cart/CartList.tsx
  src/components/Shop/ProductItem.tsx
  src/components/common/TheHeader.tsx
  src/components/common/TheModal.tsx
  src/reducers/selectedCart.ts
  src/routes/Admin/AdminProduct.tsx
  src/routes/Buy/Buy.tsx
  src/routes/Cart/Cart.tsx
  src/routes/Home/Home.tsx
  src/routes/Login/Login.tsx
  src/routes/Mypage/MyBankAccount.tsx
  src/routes/Mypage/MyInfo.tsx
  src/routes/Mypage/MyOrder.tsx
  src/routes/Mypage/MyOrderDetails.tsx
  src/routes/Mypage/Mypage.tsx
  src/routes/Shop/Shop.tsx
  src/routes/Shop/ShopDetail.tsx
  src/utils/convert.ts
Labels: enhancement

#147 Feat(fe): ShopDetail에서 Buy 페이지 라우팅 인가/인증 추가
  src/routes/Shop/ShopDetail.tsx
Labels: enhancement
